name: Build and Publish to TestPyPI

on:
  workflow_dispatch:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Extract version from pyproject.toml
        id: version
        run: |
          version=$(grep '^version *= *' pyproject.toml | sed -E 's/version *= *"([^"]+)"/\1/')
          echo "version=$version" >> "$GITHUB_OUTPUT"

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install build tools
        run: |
          python -m pip install --upgrade pip
          pip install build twine

      - name: Build distribution
        run: |
          rm -rf dist/
          python -m build

      - name: Upload to TestPyPI
        if: github.event_name == 'push'
        run: twine upload --repository-url https://test.pypi.org/legacy/ dist/*
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.TEST_PYPI_TOKEN }}

  test-install:
    runs-on: ubuntu-latest
    needs: build-and-publish
    steps:
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install published package from TestPyPI
        run: |
          pip install --no-cache-dir -i https://test.pypi.org/simple/ \
            --extra-index-url https://pypi.org/simple exargs-qiaoy

      - name: Run unit tests
        run: python -m unittest discover -s exargs_test
